# Generated by Django 3.1.6 on 2021-02-22 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=50, verbose_name='film name')),
                ('film_description', models.CharField(max_length=150, verbose_name='film description')),
                ('film_duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='FilmType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmtype_name', models.CharField(max_length=20, verbose_name='film-type name')),
                ('filmtype_description', models.CharField(max_length=80, verbose_name='film-type description')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_name', models.CharField(max_length=20, verbose_name='gender name')),
                ('gender_description', models.CharField(max_length=100, verbose_name='gender description')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=20, verbose_name='genre name')),
                ('gender_description', models.CharField(max_length=100, verbose_name='genre description')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_full_name', models.CharField(max_length=60, verbose_name='full name')),
                ('person_date_of_birth', models.DateField()),
                ('person_date_of_death', models.DateField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gender')),
            ],
        ),
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roletype_name', models.CharField(max_length=15, verbose_name='role-type name')),
                ('roletype_description', models.CharField(max_length=100, verbose_name='role-type description')),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_name', models.CharField(max_length=60, verbose_name='studio name')),
                ('studio_description', models.CharField(max_length=200, verbose_name='studio description')),
                ('studio_foundation_date', models.DateField()),
                ('studio_dissolution_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.film')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
                ('roletype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.roletype')),
            ],
        ),
        migrations.CreateModel(
            name='FilmToStudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.film')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studio')),
            ],
        ),
        migrations.CreateModel(
            name='FilmToGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.film')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genre')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='filmtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.filmtype'),
        ),
    ]
