# Generated by Django 3.1.6 on 2021-02-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210222_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='film description'),
        ),
        migrations.AlterField(
            model_name='filmtype',
            name='filmtype_description',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='film-type description'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='gender_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='gender description'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='gender_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='genre description'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roletype',
            name='roletype_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='role-type description'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='studio_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='studio description'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='studio_dissolution_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
